### ISSUE TITLE
愿意付费支持

### ISSUE THREAD

**Issue by byheaven** [wtsnwei/pdsp#1]
感谢翻译的工作，整理完毕后愿意付费支持。byheaven0912@gmail.com

**Comment by wtsnwei** [comment]
已发布预览版，见 releases

**Comment by byheaven** [comment]
> 已发布预览版，见 releases

谢谢！但是好像没有PDF文件，只有tex的源文件

**Comment by wtsnwei** [comment]
已加上
![图片](https://user-images.githubusercontent.com/42241753/128437398-592c0f85-c98d-4098-b0b4-7a8fe399f8b4.png)
